version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: sequence-db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=sequence_db
    ports:
      - "5432:5432" # Mapping: [Host Port]:[Container Port]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: